name: "Reusable Workflows CI for Java Maven"

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      environment:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      shell:
        required: true
        type: string
      project-name:
        required: true
        type: string      
      java-distribution:
        required: true
        type: string
      java-version:
        required: true
        type: string           
      maven-version:
        required: true
        type: string      

jobs:
  Build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        shell: ${{ inputs.shell }}
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
      
      - name: "Check Wrapper Exists"
        run: |
          count_maven=$(find . -type f -name pom.xml 2>/dev/null | wc -l)
          if [ "${count_maven}" -ge "1" ]; then
            echo "setup_maven=false" >> $GITHUB_ENV
          else
            echo "setup_maven=true" >> $GITHUB_ENV
          fi

      - name: Set up Maven
        if: ${{ env.setup_maven == true }}
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: ${{ inputs.maven-version }}
      
      - name: Maven Clean and Package
        run: |
          if [[ ${{ env.setup_maven }} ]]; then
            echo "Utilizando do instalador"
            mvn clean package -DskipTests -DskipITs -f pom.xml -s settings.xml
          else
            echo "Utilizando Wrapper"
            ./mvnw clean package -DskipTests -DskipITs -f pom.xml -s settings.xml
          fi


      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.project-name }}
          path: ${{ github.workspace }}/${{ inputs.working-directory }}/target/

  Test:
    name: Test
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        shell: ${{ inputs.shell }}
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: ${{ inputs.maven-version }}

      - name: Maven clean and test
        run: |
          echo "Antes de empacotar"
          ls -lrth --color
          mvn clean test -f pom.xml -s settings.xml
          mvn jacoco:report surefire-report:report-only -f pom.xml -s settings.xml
          echo "Depois de empacotar"
          ls -lrth --color

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.project-name }}
          path: |
            ${{ github.workspace }}/${{ inputs.working-directory }}/target/jacoco.exec
            ${{ github.workspace }}/${{ inputs.working-directory }}/target/site